"""create tasks table

Revision ID: aa2d47b29c73
Revises: 
Create Date: 2026-02-07 16:42:46.101655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2d47b29c73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factorytasks_schema_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_factorytasks_schema_tasks_title'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('ix_factorytasks_schema_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_factorytasks_schema_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###
